name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        run: |
          git config --global user.email "developerbiodun@gmail.com"
          git config --global user.name "production-app"
          git remote set-url origin https://cbdf44ac015a2cc1698a215f324067f6c007577a@github.com/production-app/material-ui-dashboard.git
          npm run deploy
